import { Injectable } from '@angular/core';

@Injectable()
export class DataFormService {

  private dataEntryForm = {
    Id: ['1'],
    Product_Info_1: ['1'],
    Product_Info_2: ['D3'],
    Product_Info_3: ['26'],
    Product_Info_4: ['0.487179487'],
    Product_Info_5: ['2'],
    Product_Info_6: ['3'],
    Product_Info_7: ['1'],
    Ins_Age: ['0.611940299'],
    Ht: ['0.781818182'],
    Wt: ['0.338912134'],
    BMI: ['0.472261563'],
    Employment_Info_1: ['0.15'],
    Employment_Info_2: ['3'],
    Employment_Info_3: ['1'],
    Employment_Info_4: ['0'],
    Employment_Info_5: ['2'],
    Employment_Info_6: ['0.5'],
    InsuredInfo_1: ['2'],
    InsuredInfo_2: ['2'],
    InsuredInfo_3: ['11'],
    InsuredInfo_4: ['3'],
    InsuredInfo_5: ['1'],
    InsuredInfo_6: ['1'],
    InsuredInfo_7: ['1'],
    Insurance_History_1: ['2'],
    Insurance_History_2: ['1'],
    Insurance_History_3: ['1'],
    Insurance_History_4: ['3'],
    Insurance_History_5: ['0'],
    Insurance_History_6: ['0'],
    Insurance_History_7: ['3'],
    Insurance_History_8: ['2'],
    Insurance_History_9: ['3'],
    Family_Hist_1: ['3'],
    Family_Hist_2: ['0'],
    Family_Hist_3: ['0.62745098'],
    Family_Hist_4: ['0.76056338'],
    Family_Hist_5: ['0'],
    Medical_History_1: ['2'],
    Medical_History_2: ['16'],
    Medical_History_3: ['2'],
    Medical_History_4: ['2'],
    Medical_History_5: ['1'],
    Medical_History_6: ['3'],
    Medical_History_7: ['1'],
    Medical_History_8: ['2'],
    Medical_History_9: ['2'],
    Medical_History_10: [''],
    Medical_History_11: ['3'],
    Medical_History_12: ['2'],
    Medical_History_13: ['1'],
    Medical_History_14: ['3'],
    Medical_History_15: [''],
    Medical_History_16: ['1'],
    Medical_History_17: ['2'],
    Medical_History_18: ['1'],
    Medical_History_19: ['1'],
    Medical_History_20: ['2'],
    Medical_History_21: ['1'],
    Medical_History_22: ['2'],
    Medical_History_23: ['1'],
    Medical_History_24: [''],
    Medical_History_25: ['2'],
    Medical_History_26: ['2'],
    Medical_History_27: ['1'],
    Medical_History_28: ['1'],
    Medical_History_29: ['3'],
    Medical_History_30: ['2'],
    Medical_History_31: ['3'],
    Medical_History_32: [''],
    Medical_History_33: ['3'],
    Medical_History_34: ['3'],
    Medical_History_35: ['1'],
    Medical_History_36: ['3'],
    Medical_History_37: ['2'],
    Medical_History_38: ['1'],
    Medical_History_39: ['3'],
    Medical_History_40: ['3'],
    Medical_History_41: ['3'],
    // Medical_Keyword_1: ['0'],
    // Medical_Keyword_2: ['0'],
    // Medical_Keyword_3: ['0'],
    // Medical_Keyword_4: ['0'],
    // Medical_Keyword_5: ['0'],
    // Medical_Keyword_6: ['0'],
    // Medical_Keyword_7: ['0'],
    // Medical_Keyword_8: ['0'],
    // Medical_Keyword_9: ['0'],
    // Medical_Keyword_10: ['0'],
    // Medical_Keyword_11: ['0'],
    // Medical_Keyword_12: ['0'],
    // Medical_Keyword_13: ['0'],
    // Medical_Keyword_14: ['0'],
    // Medical_Keyword_15: ['1'],
    // Medical_Keyword_16: ['0'],
    // Medical_Keyword_17: ['0'],
    // Medical_Keyword_18: ['0'],
    // Medical_Keyword_19: ['1'],
    // Medical_Keyword_20: ['0'],
    // Medical_Keyword_21: ['0'],
    // Medical_Keyword_22: ['0'],
    // Medical_Keyword_23: ['0'],
    // Medical_Keyword_24: ['0'],
    // Medical_Keyword_25: ['1'],
    // Medical_Keyword_26: ['0'],
    // Medical_Keyword_27: ['0'],
    // Medical_Keyword_28: ['0'],
    // Medical_Keyword_29: ['0'],
    // Medical_Keyword_30: ['0'],
    // Medical_Keyword_31: ['0'],
    // Medical_Keyword_32: ['0'],
    // Medical_Keyword_33: ['0'],
    // Medical_Keyword_34: ['0'],
    // Medical_Keyword_35: ['0'],
    // Medical_Keyword_36: ['0'],
    // Medical_Keyword_37: ['0'],
    // Medical_Keyword_38: ['0'],
    // Medical_Keyword_39: ['0'],
    // Medical_Keyword_40: ['0'],
    // Medical_Keyword_41: ['0'],
    // Medical_Keyword_42: ['0'],
    // Medical_Keyword_43: ['0'],
    // Medical_Keyword_44: ['0'],
    // Medical_Keyword_45: ['0'],
    // Medical_Keyword_46: ['0'],
    // Medical_Keyword_47: ['0'],
    // Medical_Keyword_48: ['0'],
  }

  constructor() { }

  getDataEntryForm() {
    return this.dataEntryForm;
  }

}
